// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtsgFoviSrUNLJGcu9rvBlJoWIoeiY1uw',
    appId: '1:94228357291:android:dff4e7ec6039ab34fdd7ee',
    messagingSenderId: '94228357291',
    projectId: 'chat39-cff7b',
    storageBucket: 'chat39-cff7b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZGT6BIfIgiJjNZ03J0TvKnsX39__ISIE',
    appId: '1:94228357291:ios:ff083a367756643efdd7ee',
    messagingSenderId: '94228357291',
    projectId: 'chat39-cff7b',
    storageBucket: 'chat39-cff7b.appspot.com',
    androidClientId: '94228357291-5a156kghaj1k0sm9on0du8j4j4r0ev9t.apps.googleusercontent.com',
    iosClientId: '94228357291-9b7o9n4khsi23bre5b4sirjc1okj01sp.apps.googleusercontent.com',
    iosBundleId: 'com.example.chat39',
  );
}
